@echo off
echo Installing dependencies...
call npm install
echo Generating Prisma Client...
call npx prisma generate
echo Pushing DB Schema...
call npx prisma db push
echo Seeding Data...
call npx prisma db seed
echo DONE!
